--Añado mis llaves primarias y modifico los campos not null de mis TABLAS que sean posibles
--TABLAS FUERTES
--TABLA PROYECTOS
ALTER TABLE proyectos ADD CONSTRAINT PK_ID_PROYECTO PRIMARY KEY(id_proyecto);

ALTER TABLE proyectos ADD CONSTRAINT NN_NOMBRE_PROYECTO CHECK(nombre_proyecto IS NOT NULL);

ALTER TABLE proyectos ADD CONSTRAINT NN_INTRODUCCION CHECK(introduccion IS NOT NULL);

ALTER TABLE proyectos ADD CONSTRAINT NN_FECHA_CREACION CHECK(fecha_creacion IS NOT NULL);

--TABLA TIPOS
ALTER TABLE tipos ADD CONSTRAINT PK_ID_TIPO PRIMARY KEY (id_tipo);

ALTER TABLE tipos ADD CONSTRAINT NN_TIPO_USUARIO CHECK(tipo_usuario IS NOT NULL);

--TABLA ESTADOS
ALTER TABLE estados ADD CONSTRAINT PK_ID_ESTADO PRIMARY KEY(id_estado);

ALTER TABLE estados ADD CONSTRAINT NN_ESTADO CHECK(estado IS NOT NULL);

--TABLAS DEBILES
--TABLA USUARIOS 
ALTER TABLE usuarios ADD CONSTRAINT PK_ID_USUARIO PRIMARY KEY(id_usuario);

ALTER TABLE usuarios ADD CONSTRAINT NN_NOMBRE CHECK(nombre IS NOT NULL);

ALTER TABLE usuarios ADD CONSTRAINT NN_PAPELLIDO CHECK(papellido IS NOT NULL);

ALTER TABLE usuarios ADD CONSTRAINT NN_CORREO CHECK(correo IS NOT NULL);

ALTER TABLE usuarios ADD CONSTRAINT NN_CONTRASENA CHECK(contrasena IS NOT NULL);

ALTER TABLE usuarios ADD CONSTRAINT NN_FECHA_REGISTRO CHECK(fecha_registro IS NOT NULL);

--CREACIÓN DE NUESTRAS LLAVES FORANEAS SEGÚN LA LOGICA DE NUESTRO APLICATIVO
--TABLA USUARIO
ALTER TABLE usuarios ADD CONSTRAINT FK_CODIGO_TIPO_TIPOS FOREIGN KEY(codigo_tipo) REFERENCES tipos(id_tipo);

ALTER TABLE usuarios ADD CONSTRAINT NN_CODIGO_TIPO CHECK(codigo_tipo IS NOT NULL);

ALTER TABLE usuarios ADD CONSTRAINT FK_CODIGO_ESTADO_ESTADOS FOREIGN KEY(codigo_estado) REFERENCES estados(id_estado);

ALTER TABLE usuarios ADD CONSTRAINT NN_CODIGO_ESTADO CHECK(codigo_estado IS NOT NULL );


--CREACIÓN DE NUESTROS CONSTRAINT PARA LA TABLA REFERENCIA DE USUARIOS Y PROYECTOS SEGÚN LA LÓGICA DE NUESTRO APLICATIVO
ALTER TABLE proyectos_usuarios ADD CONSTRAINT PK_PROYECTOS_USUARIOS PRIMARY KEY(codigo_proyecto,codigo_usuario);

ALTER TABLE proyectos_usuarios ADD CONSTRAINT FK_CODIGO_PROYECTO_PROYECTOS FOREIGN KEY(codigo_proyecto) REFERENCES proyectos(id_proyecto);

ALTER TABLE proyectos_usuarios ADD CONSTRAINT FK_CODIGO_USUARIO_USUARIOS FOREIGN KEY(codigo_usuario) REFERENCES usuarios(id_usuario);

--CONSTRAINTS TABLA DE REFERENCIA ENTRE PROYECTOS Y USUARIOS, ADICIONANDO SUS AVANCES CON RETROALIMENTACIÓN
ALTER TABLE avances ADD CONSTRAINT PK_AVANCES PRIMARY KEY(codigo_proyecto,codigo_usuario);

ALTER TABLE avances ADD CONSTRAINT FK_CODIGO_PROYECTO_AVANCES_PROYECTOS FOREIGN KEY(codigo_proyecto) REFERENCES proyectos(id_proyecto);

ALTER TABLE avances ADD CONSTRAINT FK_CODIGO_USUARIO_AVANCES_USUARIOS FOREIGN KEY(codigo_usuario) REFERENCES usuarios(id_usuario);

ALTER TABLE avances ADD CONSTRAINT NN_DESCRIPCION_AVANCE CHECK(descripcion_avance IS NOT NULL);

ALTER TABLE avances ADD CONSTRAINT FK_CODIGO_COORDINADOR_USUARIOS FOREIGN KEY(codigo_coordinador) REFERENCES usuarios(id_usuario);