DROP VIEW vista_usuarios_estados_tipos; 

CREATE VIEW vista_usuarios_estados_tipos 
AS(SELECT NOMBRE, PAPELLIDO,CORREO,TIPO_USUARIO,ESTADO FROM USUARIOS 
INNER JOIN TIPOS ON ID_TIPO=CODIGO_TIPO
INNER JOIN ESTADOS ON ID_ESTADO=CODIGO_ESTADO);